/* Accounts Payable / Hutang Vendor */
(function(){
  DB.payables=DB.payables||[];
  const navIndex=NAV.findIndex(x=>x[0]==='pembelian');
  if(!NAV.some(x=>x[0]==='hutang-vendor')) NAV.splice(navIndex<0?NAV.length:navIndex+1,0,['hutang-vendor','◫','Hutang Vendor']);
  const dateOnly=v=>v?new Date(v).toISOString().slice(0,10):'';
  const dateText=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';
  const money=v=>fmt(Math.round(Number(v)||0));
  const today=()=>dateOnly(Date.now());
  function termDays(s){const n=parseInt(String(s||'').match(/\d+/)?.[0]||'30',10);return Number.isFinite(n)?n:30;}
  function poAmount(po){const byLines=(po.items||[]).reduce((a,it)=>a+(Number(it.cost)||0)*(Number(it.displayQty??it.qty)||0),0);return Math.round(byLines||Number(po.value)||0);}
  function completedReturns(poId){return (DB.purchaseReturns||[]).filter(r=>r.poId===poId&&r.status==='Selesai').reduce((a,r)=>a+(Number(r.value)||0),0);}
  function effectiveAmount(p){return Math.max(0,(Number(p.amount)||0)-completedReturns(p.poId));}
  function paid(p){return (p.payments||[]).reduce((a,x)=>a+(Number(x.amount)||0),0);}
  function remaining(p){return Math.max(0,effectiveAmount(p)-paid(p));}
  function updateStatus(p){const rem=remaining(p);p.paidAmount=paid(p);p.adjustedAmount=effectiveAmount(p);p.status=rem<=0?'Lunas':p.paidAmount>0?'Lunas Sebagian':'Belum Lunas';return p;}
  function isOverdue(p){return p.status!=='Lunas'&&p.dueDate&&p.dueDate<today();}
  function createPayables(){
    (DB.purchaseOrders||[]).filter(po=>po.status==='Selesai').forEach(po=>{
      if(DB.payables.some(p=>p.poId===po.id))return;
      const supplier=DB.suppliers?.find(s=>s.id===po.supplierId)||{};
      const received=po.receivedAt||po.date||Date.now();const due=new Date(received);due.setDate(due.getDate()+termDays(supplier.paymentTerm));
      DB.payables.push({id:uid('ap'),supplierId:po.supplierId||'',poId:po.id,amount:poAmount(po),dueDate:dateOnly(due),paidAmount:0,status:'Belum Lunas',payments:[],createdAt:Date.now()});
    });
    DB.payables.forEach(updateStatus);saveDB();
  }
  function journalPayment(payable,payment){
    if(!DB.journal)return;const sourceId=payable.id+'-'+payment.id;
    if(DB.journal.some(j=>j.sourceType==='PayablePayment'&&j.sourceId===sourceId))return;
    DB.journal.push({id:uid('j'),date:payment.date,sourceType:'PayablePayment',sourceId,note:`Pembayaran hutang ${payable.code||payable.id}`,entries:[{account:'2000',debit:Math.round(payment.amount),credit:0},{account:'1000',debit:0,credit:Math.round(payment.amount)}]});
  }
  function supplierName(id){return (DB.suppliers||[]).find(s=>s.id===id)?.name||'-';}
  function poCode(id){return (DB.purchaseOrders||[]).find(p=>p.id===id)?.code||'-';}
  function getPayable(){return DB.payables.find(p=>p.id===S.selectedPayableId);}
  function filter(){return S.apFilter||(S.apFilter={status:'Semua',supplier:'Semua',search:''});}
  function visible(){const f=filter();return [...DB.payables].filter(p=>{updateStatus(p);const q=(f.search||'').toLowerCase();if(f.status!=='Semua'&&p.status!==f.status)return false;if(f.supplier!=='Semua'&&p.supplierId!==f.supplier)return false;if(q&&!(supplierName(p.supplierId)+' '+poCode(p.poId)+' '+p.id).toLowerCase().includes(q))return false;return true;}).sort((a,b)=>String(a.dueDate||'9999').localeCompare(String(b.dueDate||'9999')));}
  function statusBadge(p){return isOverdue(p)?status('Jatuh Tempo','expired'):status(p.status,p.status==='Lunas'?'ok':p.status==='Lunas Sebagian'?'warn':'violet');}
  function listPage(){const list=visible(),all=DB.payables||[],open=all.filter(p=>{updateStatus(p);return p.status!=='Lunas';}),out=open.reduce((a,p)=>a+remaining(p),0),over=open.filter(isOverdue).reduce((a,p)=>a+remaining(p),0);const f=filter();return `<section class="page active"><div class="head"><div><h2>Hutang Vendor</h2><p>Monitor payable dari PO selesai, jatuh tempo, dan pembayaran cicilan vendor.</p></div><button class="outline" data-ap-sync>Sinkronkan Payable</button></div><div class="grid4"><div class="card kpi"><div class="kicon">◫</div><div><label>Hutang Berjalan</label><strong>${money(out)}</strong><span class="muted">Belum lunas</span></div></div><div class="card kpi"><div class="kicon">!</div><div><label>Jatuh Tempo</label><strong>${money(over)}</strong><span class="muted">Per hari ini</span></div></div><div class="card kpi"><div class="kicon">◴</div><div><label>Belum Lunas</label><strong>${open.filter(p=>p.status==='Belum Lunas').length}</strong><span class="muted">Dokumen</span></div></div><div class="card kpi"><div class="kicon">✓</div><div><label>Lunas Sebagian</label><strong>${open.filter(p=>p.status==='Lunas Sebagian').length}</strong><span class="muted">Dokumen</span></div></div></div><div style="height:16px"></div><div class="card"><div class="tools"><input class="flex" id="apSearch" value="${esc(f.search||'')}" placeholder="Cari vendor atau nomor PO..."><select id="apStatus"><option>Semua</option>${['Belum Lunas','Lunas Sebagian','Lunas'].map(x=>`<option ${f.status===x?'selected':''}>${x}</option>`).join('')}</select><select id="apSupplier"><option value="Semua">Semua Vendor</option>${(DB.suppliers||[]).map(s=>`<option value="${s.id}" ${f.supplier===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select><button class="outline" id="apReset">Reset</button></div><table><thead><tr><th>Vendor</th><th>PO</th><th>Jatuh Tempo</th><th>Nilai Awal</th><th>Retur</th><th>Dibayar</th><th>Sisa Hutang</th><th>Status</th></tr></thead><tbody>${list.length?list.map(p=>`<tr class="clickable" data-ap-open="${p.id}"><td><b>${esc(supplierName(p.supplierId))}</b></td><td>${esc(poCode(p.poId))}</td><td>${esc(p.dueDate||'-')}</td><td>${money(p.amount)}</td><td>${money(completedReturns(p.poId))}</td><td>${money(paid(p))}</td><td><b>${money(remaining(p))}</b></td><td>${statusBadge(p)}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">Tidak ada hutang sesuai filter.</td></tr>'}</tbody></table></div></section>`;}
  function detailPage(p){if(!p){S.selectedPayableId=null;return listPage();}updateStatus(p);const source=(DB.purchaseOrders||[]).find(x=>x.id===p.poId),supplier=(DB.suppliers||[]).find(s=>s.id===p.supplierId)||{};return `<section class="page active"><div class="head"><div><button class="outline" data-ap-back>← Kembali ke Hutang Vendor</button><h2 style="margin-top:14px">Detail Hutang Vendor</h2><p>${esc(poCode(p.poId))} · ${esc(supplier.name||'-')}</p></div>${p.status!=='Lunas'?`<button class="primary" data-ap-pay="${p.id}">＋ Catat Pembayaran</button>`:''}</div><div class="card" style="padding:18px"><div class="grid4"><div><label class="muted">Vendor</label><b>${esc(supplier.name||'-')}</b></div><div><label class="muted">Termin</label><b>${esc(supplier.paymentTerm||'30 Hari')}</b></div><div><label class="muted">Jatuh Tempo</label><b>${esc(p.dueDate||'-')}</b></div><div><label class="muted">Status</label><p>${statusBadge(p)}</p></div></div></div><div style="height:16px"></div><div class="two"><div class="card"><div class="title"><span>Ringkasan Hutang</span></div><table><tbody><tr><td>Nilai PO</td><td><b>${money(p.amount)}</b></td></tr><tr><td>Potongan Retur Pembelian</td><td><b>(${money(completedReturns(p.poId))})</b></td></tr><tr><td>Nilai Hutang Efektif</td><td><b>${money(effectiveAmount(p))}</b></td></tr><tr><td>Sudah Dibayar</td><td><b>${money(paid(p))}</b></td></tr><tr><td><b>Sisa Hutang</b></td><td><b style="color:var(--g)">${money(remaining(p))}</b></td></tr></tbody></table></div><div class="card"><div class="title"><span>PO Asal</span></div><p><b>${esc(source?.code||'-')}</b></p><p class="muted">Tanggal terima: ${dateText(source?.receivedAt||source?.date)}</p><p class="muted">Catatan: ${esc(source?.note||'-')}</p></div></div><div style="height:16px"></div><div class="card"><div class="title"><span>Riwayat Pembayaran</span><span class="muted">${(p.payments||[]).length} pembayaran</span></div><table><thead><tr><th>Tanggal</th><th>Metode</th><th>Jumlah</th></tr></thead><tbody>${(p.payments||[]).length?(p.payments||[]).map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.method)}</td><td><b>${money(x.amount)}</b></td></tr>`).join(''):'<tr><td colspan="3" class="empty">Belum ada pembayaran.</td></tr>'}</tbody></table></div></section>`;}
  function pay(id){const p=DB.payables.find(x=>x.id===id);if(!p)return;updateStatus(p);modal('Catat Pembayaran Hutang',`<div class="form"><div class="card" style="padding:10px"><b>${esc(supplierName(p.supplierId))}</b><br><small class="muted">PO ${esc(poCode(p.poId))} · Sisa hutang ${money(remaining(p))}</small></div><label>Tanggal Pembayaran<input id="apPayDate" type="date" value="${today()}"></label><label>Metode Pembayaran<select id="apPayMethod"><option>Transfer Bank</option><option>Tunai</option><option>Giro</option><option>Lainnya</option></select></label><label>Jumlah Pembayaran<input id="apPayAmount" type="number" min="1" max="${remaining(p)}" value="${remaining(p)}"></label></div>`,()=>{const amount=Number(document.querySelector('#apPayAmount').value)||0;if(!(amount>0)||amount>remaining(p))return toast('Jumlah pembayaran tidak valid','err'),false;const payment={id:uid('pay'),date:new Date(document.querySelector('#apPayDate').value||today()).getTime(),amount,method:document.querySelector('#apPayMethod').value};p.payments=p.payments||[];p.payments.push(payment);updateStatus(p);journalPayment(p,payment);saveDB();render();toast('Pembayaran hutang dicatat');},{saveLabel:'Simpan Pembayaran'});}
  function injectVendorPayable(){if(S.page!=='vendor'||!S.selectedVendorId)return;const vendor=(DB.suppliers||[]).find(s=>s.id===S.selectedVendorId),page=document.querySelector('#pages .page');if(!vendor||!page||document.querySelector('#vendorPayables'))return;const ps=(DB.payables||[]).filter(p=>p.supplierId===vendor.id).map(updateStatus),open=ps.filter(p=>p.status!=='Lunas'),total=open.reduce((a,p)=>a+remaining(p),0);const box=document.createElement('div');box.id='vendorPayables';box.className='card';box.style.marginTop='16px';box.innerHTML=`<div class="title"><span>Hutang Berjalan</span><span class="muted">${open.length} dokumen</span></div><div class="grid4"><div><label class="muted">Total Hutang</label><h2>${money(total)}</h2></div><div><label class="muted">Jatuh Tempo</label><h2>${money(open.filter(isOverdue).reduce((a,p)=>a+remaining(p),0))}</h2></div><div><label class="muted">Belum Lunas</label><h2>${open.filter(p=>p.status==='Belum Lunas').length}</h2></div><div><label class="muted">Cicilan</label><h2>${open.filter(p=>p.status==='Lunas Sebagian').length}</h2></div></div>${open.length?`<table><thead><tr><th>PO</th><th>Jatuh Tempo</th><th>Sisa</th><th>Status</th></tr></thead><tbody>${open.slice(0,5).map(p=>`<tr><td>${esc(poCode(p.poId))}</td><td>${esc(p.dueDate)}</td><td>${money(remaining(p))}</td><td>${statusBadge(p)}</td></tr>`).join('')}</tbody></table>`:'<p class="empty">Tidak ada hutang berjalan.</p>'}`;page.appendChild(box);}
  createPayables();
  const baseRender=render;render=function(){if(S.page==='hutang-vendor'){createPayables();nav();document.querySelector('#pages').innerHTML=S.selectedPayableId?detailPage(getPayable()):listPage();bind();return;}baseRender();injectVendorPayable();};
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;S.selectedPayableId=null;render();});document.querySelectorAll('[data-ap-sync]').forEach(b=>b.onclick=()=>{createPayables();render();toast('Payable sudah disinkronkan');});document.querySelectorAll('[data-ap-open]').forEach(b=>b.onclick=()=>{S.selectedPayableId=b.dataset.apOpen;render();});document.querySelectorAll('[data-ap-back]').forEach(b=>b.onclick=()=>{S.selectedPayableId=null;render();});document.querySelectorAll('[data-ap-pay]').forEach(b=>b.onclick=()=>pay(b.dataset.apPay));const f=filter();const s=document.querySelector('#apSearch');if(s)s.oninput=()=>{f.search=s.value;render();};const st=document.querySelector('#apStatus');if(st)st.onchange=()=>{f.status=st.value;render();};const sp=document.querySelector('#apSupplier');if(sp)sp.onchange=()=>{f.supplier=sp.value;render();};const rs=document.querySelector('#apReset');if(rs)rs.onclick=()=>{S.apFilter={status:'Semua',supplier:'Semua',search:''};render();};}
})();
