/* General Ledger sederhana: jurnal otomatis dari dokumen operasional */
(function(){
  const DEFAULT_COA=[
    {code:'1000',name:'Kas',class:'Aset'},
    {code:'1100',name:'Piutang Usaha',class:'Aset'},
    {code:'1200',name:'Persediaan Obat',class:'Aset'},
    {code:'2000',name:'Hutang Usaha',class:'Liabilitas'},
    {code:'4000',name:'Pendapatan Penjualan',class:'Pendapatan'},
    {code:'4100',name:'Pendapatan Penyesuaian Persediaan',class:'Pendapatan'},
    {code:'5000',name:'HPP (Harga Pokok Penjualan)',class:'Beban'},
    {code:'5100',name:'Beban Penyesuaian Persediaan',class:'Beban'}
  ];
  DB.chartOfAccounts=DB.chartOfAccounts||[];DEFAULT_COA.forEach(a=>{if(!DB.chartOfAccounts.some(x=>x.code===a.code))DB.chartOfAccounts.push(a);});
  DB.journal=DB.journal||[];
  const navAt=NAV.findIndex(x=>x[0]==='laporan-golongan');
  if(!NAV.some(x=>x[0]==='general-ledger'))NAV.splice(navAt<0?NAV.length:navAt+1,0,['general-ledger','▤','General Ledger']);
  if(!NAV.some(x=>x[0]==='laporan-keuangan'))NAV.splice(navAt<0?NAV.length:navAt+2,0,['laporan-keuangan','◫','Laporan Keuangan']);
  const dateText=v=>v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';
  const dateOnly=v=>v?new Date(v).toISOString().slice(0,10):'';
  const money=v=>fmt(Math.round(Number(v)||0));
  function baseQty(it){const p=DB.products.find(x=>x.id===it.productId);const u=p?.units?.find(x=>x.code===it.unitCode)||p?.units?.find(x=>x.code===p?.baseUnit);return Number(it.baseQty??((Number(it.qty)||0)*(Number(u?.factorToBase)||1)))||0;}
  function baseCost(it){const p=DB.products.find(x=>x.id===it.productId);const b=p?.units?.find(x=>x.code===p?.baseUnit);return Number(it.costBase??b?.cost??p?.cost??0)||0;}
  function hpp(items){return (items||[]).reduce((a,it)=>a+baseQty(it)*baseCost(it),0);}
  function debit(account,amount){return {account,debit:Math.round(amount||0),credit:0};}
  function credit(account,amount){return {account,debit:0,credit:Math.round(amount||0)};}
  function addJournal(sourceType,sourceId,date,entries,note){if(!sourceId||DB.journal.some(j=>j.sourceType===sourceType&&j.sourceId===sourceId))return;const clean=entries.filter(e=>e.debit||e.credit);const d=clean.reduce((a,e)=>a+e.debit,0),c=clean.reduce((a,e)=>a+e.credit,0);if(!clean.length||d!==c)return;DB.journal.push({id:uid('j'),date:date||Date.now(),sourceType,sourceId,note:note||'',entries:clean});}
  function postSales(){(DB.transactions||[]).forEach(tx=>{const revenue=Number(tx.total)||0,cost=hpp(tx.items),cashAccount=(tx.payment==='Kredit'||tx.payment==='Piutang')?'1100':'1000';addJournal('Sale',tx.id,tx.time,[debit(cashAccount,revenue),credit('4000',revenue),debit('5000',cost),credit('1200',cost)],`Penjualan ${tx.code||''}`);});}
  function postPurchases(){(DB.purchaseOrders||[]).filter(po=>po.status==='Selesai').forEach(po=>{const val=(po.items||[]).reduce((a,it)=>a+(Number(it.cost)||0)*(Number(it.displayQty??it.qty)||0),0)||Number(po.value)||0;addJournal('Purchase',po.id,po.receivedAt||po.date,[debit('1200',val),credit('2000',val)],`Penerimaan PO ${po.code||''}`);});}
  function postReturns(){(DB.purchaseReturns||[]).filter(r=>r.status==='Selesai').forEach(r=>{const val=Number(r.value)||0;addJournal('PurchaseReturn',r.id,r.completedAt||r.date,[debit('2000',val),credit('1200',val)],`Retur pembelian ${r.code||''}`);});(DB.salesReturns||[]).filter(r=>r.status==='Selesai').forEach(r=>{const val=Number(r.value)||0,cost=hpp(r.items),acc=r.refundMethod==='Kredit Poin'?'4000':'1000';addJournal('SalesReturn',r.id,r.completedAt||r.date,[debit('4000',val),credit(acc,val),debit('1200',cost),credit('5000',cost)],`Retur penjualan ${r.code||''}`);});}
  function postAdjustments(){(DB.stockOpnames||[]).filter(s=>s.status==='Selesai').forEach(so=>{const inc=(so.items||[]).filter(i=>Number(i.diff)>0).reduce((a,i)=>a+Number(i.diff)*baseCost(i),0),dec=(so.items||[]).filter(i=>Number(i.diff)<0).reduce((a,i)=>a+Math.abs(Number(i.diff))*baseCost(i),0);if(inc)addJournal('AdjustmentIn',so.id+'-in',so.completedAt||so.date,[debit('1200',inc),credit('4100',inc)],`Adjustment stok masuk ${so.code||''}`);if(dec)addJournal('AdjustmentOut',so.id+'-out',so.completedAt||so.date,[debit('5100',dec),credit('1200',dec)],`Adjustment stok keluar ${so.code||''}`);});}
  function sync(){postSales();postPurchases();postReturns();postAdjustments();saveDB();}
  sync();
  function filter(){return S.glFilter||(S.glFilter={start:'',end:'',account:'Semua',search:''});}
  function journals(){const f=filter();return [...DB.journal].filter(j=>{const d=dateOnly(j.date),q=(f.search||'').toLowerCase();if(f.start&&d<f.start)return false;if(f.end&&d>f.end)return false;if(f.account!=='Semua'&&!j.entries.some(e=>e.account===f.account))return false;if(q&&!(j.sourceType+' '+j.sourceId+' '+j.note).toLowerCase().includes(q))return false;return true;}).sort((a,b)=>(b.date||0)-(a.date||0));}
  function accountName(code){const a=DB.chartOfAccounts.find(x=>x.code===code);return a?`${a.code} · ${a.name}`:code;}
  function journalDetail(j){return `<section class="page active"><div class="head"><div><button class="outline" data-gl-back>← Kembali ke General Ledger</button><h2 style="margin-top:14px">Detail Jurnal</h2><p>${dateText(j.date)} · ${esc(j.sourceType)} · ${esc(j.note||'-')}</p></div></div><div class="card"><div class="title"><span>Jurnal ${esc(j.id)}</span><span class="muted">Sumber: ${esc(j.sourceId||'-')}</span></div><table><thead><tr><th>Akun</th><th>Debit</th><th>Kredit</th></tr></thead><tbody>${j.entries.map(e=>`<tr><td><b>${esc(accountName(e.account))}</b></td><td>${e.debit?money(e.debit):'-'}</td><td>${e.credit?money(e.credit):'-'}</td></tr>`).join('')}</tbody><tfoot><tr><td><b>Total</b></td><td><b>${money(j.entries.reduce((a,e)=>a+e.debit,0))}</b></td><td><b>${money(j.entries.reduce((a,e)=>a+e.credit,0))}</b></td></tr></tfoot></table></div></section>`;}
  function glPage(){const list=journals(),f=filter();return `<section class="page active"><div class="head"><div><h2>General Ledger Entries</h2><p>Jurnal otomatis dari penjualan, penerimaan PO, retur, dan stock adjustment.</p></div><button class="outline" data-gl-sync>Sinkronkan Jurnal</button></div><div class="card"><div class="tools"><input id="glSearch" class="flex" placeholder="Cari sumber atau keterangan..." value="${esc(f.search||'')}"><select id="glAccount"><option>Semua</option>${DB.chartOfAccounts.map(a=>`<option value="${a.code}" ${f.account===a.code?'selected':''}>${esc(a.code+' · '+a.name)}</option>`).join('')}</select><input id="glStart" type="date" value="${esc(f.start||'')}"><input id="glEnd" type="date" value="${esc(f.end||'')}"><button class="outline" id="glReset">Reset</button></div><table><thead><tr><th>Tanggal</th><th>Sumber</th><th>Keterangan</th><th>Debit</th><th>Kredit</th></tr></thead><tbody>${list.length?list.map(j=>`<tr class="clickable" data-gl-open="${j.id}"><td>${dateText(j.date)}</td><td>${esc(j.sourceType)}<br><small class="muted">${esc(j.sourceId||'-')}</small></td><td>${esc(j.note||'-')}</td><td><b>${money(j.entries.reduce((a,e)=>a+e.debit,0))}</b></td><td><b>${money(j.entries.reduce((a,e)=>a+e.credit,0))}</b></td></tr>`).join(''):'<tr><td colspan="5" class="empty">Belum ada jurnal.</td></tr>'}</tbody></table></div><div style="height:16px"></div><div class="card"><div class="title"><span>Chart of Accounts</span></div><table><thead><tr><th>Kode</th><th>Akun</th><th>Klasifikasi</th></tr></thead><tbody>${DB.chartOfAccounts.map(a=>`<tr><td><b>${esc(a.code)}</b></td><td>${esc(a.name)}</td><td>${esc(a.class)}</td></tr>`).join('')}</tbody></table></div></section>`;}
  function balances(){const map={};DB.chartOfAccounts.forEach(a=>map[a.code]={...a,debit:0,credit:0,balance:0});DB.journal.forEach(j=>(j.entries||[]).forEach(e=>{if(!map[e.account])map[e.account]={code:e.account,name:e.account,class:'Lainnya',debit:0,credit:0,balance:0};map[e.account].debit+=Number(e.debit)||0;map[e.account].credit+=Number(e.credit)||0;}));Object.values(map).forEach(a=>a.balance=['Aset','Beban'].includes(a.class)?a.debit-a.credit:a.credit-a.debit);return map;}
  function financePage(){const b=balances(),revenue=(b['4000']?.balance||0)+(b['4100']?.balance||0),expense=(b['5000']?.balance||0)+(b['5100']?.balance||0),profit=revenue-expense,assets=(b['1000']?.balance||0)+(b['1100']?.balance||0)+(b['1200']?.balance||0),liability=b['2000']?.balance||0,equity=assets-liability;return `<section class="page active"><div class="head"><div><h2>Laporan Keuangan</h2><p>Laba rugi dan ringkasan neraca dari jurnal otomatis yang sudah diposting.</p></div><button class="outline" data-gl-sync>Sinkronkan Jurnal</button></div><div class="grid4"><div class="card kpi"><div class="kicon">+</div><div><label>Pendapatan</label><strong>${money(revenue)}</strong><span class="muted">Akun 4000–4100</span></div></div><div class="card kpi"><div class="kicon">−</div><div><label>Beban / HPP</label><strong>${money(expense)}</strong><span class="muted">Akun 5000–5100</span></div></div><div class="card kpi"><div class="kicon">=</div><div><label>Laba Bersih</label><strong>${money(profit)}</strong><span class="muted">Pendapatan dikurangi beban</span></div></div><div class="card kpi"><div class="kicon">◫</div><div><label>Total Aset</label><strong>${money(assets)}</strong><span class="muted">Kas, piutang, persediaan</span></div></div></div><div style="height:16px"></div><div class="two"><div class="card"><div class="title"><span>Laba Rugi Sederhana</span></div><table><tbody><tr><td>Pendapatan Penjualan</td><td><b>${money(b['4000']?.balance||0)}</b></td></tr><tr><td>Pendapatan Penyesuaian Persediaan</td><td><b>${money(b['4100']?.balance||0)}</b></td></tr><tr><td>HPP</td><td><b>(${money(b['5000']?.balance||0)})</b></td></tr><tr><td>Beban Penyesuaian Persediaan</td><td><b>(${money(b['5100']?.balance||0)})</b></td></tr><tr><td><b>Laba Bersih</b></td><td><b style="color:var(--g)">${money(profit)}</b></td></tr></tbody></table></div><div class="card"><div class="title"><span>Neraca Dasar</span></div><table><tbody><tr><td>Kas</td><td><b>${money(b['1000']?.balance||0)}</b></td></tr><tr><td>Piutang Usaha</td><td><b>${money(b['1100']?.balance||0)}</b></td></tr><tr><td>Persediaan Obat</td><td><b>${money(b['1200']?.balance||0)}</b></td></tr><tr><td><b>Total Aset</b></td><td><b>${money(assets)}</b></td></tr><tr><td>Hutang Usaha</td><td><b>${money(liability)}</b></td></tr><tr><td>Ekuitas Sederhana</td><td><b>${money(equity)}</b></td></tr></tbody></table></div></div></section>`;}
  const baseRender=render;render=function(){if(S.page==='general-ledger'||S.page==='laporan-keuangan'){sync();nav();const p=S.page==='general-ledger'?(S.selectedJournalId?journalDetail(DB.journal.find(x=>x.id===S.selectedJournalId)||DB.journal[0]):glPage()):financePage();document.querySelector('#pages').innerHTML=p;bind();return;}baseRender();};
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;S.selectedJournalId=null;render();});document.querySelectorAll('[data-gl-sync]').forEach(b=>b.onclick=()=>{sync();render();toast('Jurnal sudah disinkronkan');});document.querySelectorAll('[data-gl-open]').forEach(b=>b.onclick=()=>{S.selectedJournalId=b.dataset.glOpen;render();});document.querySelectorAll('[data-gl-back]').forEach(b=>b.onclick=()=>{S.selectedJournalId=null;render();});const f=filter();const q=document.querySelector('#glSearch');if(q)q.oninput=()=>{f.search=q.value;render();};const a=document.querySelector('#glAccount');if(a)a.onchange=()=>{f.account=a.value;render();};const s=document.querySelector('#glStart');if(s)s.onchange=()=>{f.start=s.value;render();};const e=document.querySelector('#glEnd');if(e)e.onchange=()=>{f.end=e.value;render();};const r=document.querySelector('#glReset');if(r)r.onclick=()=>{S.glFilter={start:'',end:'',account:'Semua',search:''};render();};}
})();
