/* Price List & Diskon per Customer / Promo Periode */
(function(){
  DB.priceLists=DB.priceLists||[];
  const ni=NAV.findIndex(x=>x[0]==='pelanggan'); if(!NAV.some(x=>x[0]==='price-list')) NAV.splice(ni<0?NAV.length:ni+1,0,['price-list','🏷','Price List & Diskon']);
  const today=()=>new Date().toISOString().slice(0,10);
  const escv=v=>esc(String(v==null?'':v));
  function unit(p,code){return p?.units?.find(u=>u.code===code)||p?.units?.find(u=>u.code===p?.baseUnit)||{code:p?.baseUnit||'UNIT',label:p?.type||'Unit',factorToBase:1,price:p?.price||0,cost:p?.cost||0};}
  function normalPrice(p,code){const u=unit(p,code);return Number(u.basePrice??u.price??p.price)||0;}
  function isActive(pl,customerId,date=today()){
    if(!pl||pl.status==='Nonaktif')return false;
    if(pl.type==='Customer Group')return !!customerId&&(pl.customerIds||[]).includes(customerId);
    const r=pl.dateRange||{};return (!r.start||date>=r.start)&&(!r.end||date<=r.end);
  }
  function bestRule(productId,customerId,date=today(),basePrice){
    const candidates=[];
    (DB.priceLists||[]).filter(pl=>isActive(pl,customerId,date)).forEach(pl=>{
      const r=(pl.rules||[]).find(x=>x.productId===productId);if(!r)return;
      const price=r.fixedPrice!=null&&r.fixedPrice!==''?Number(r.fixedPrice):Math.max(0,Math.round(basePrice*(1-(Number(r.discountPercent)||0)/100)));
      if(price<basePrice)candidates.push({price,pl,rule:r});
    });
    return candidates.sort((a,b)=>a.price-b.price)[0]||null;
  }
  function cartPricing(){
    return (S.cart||[]).map(c=>{const p=DB.products.find(x=>x.id===c.id);if(!p)return null;const code=c.unitCode||p.saleUnit||p.baseUnit,basePrice=normalPrice(p,code),best=bestRule(p.id,S.cartCustomerId,today(),basePrice),price=best?best.price:basePrice;return {c,p,code,basePrice,price,best,qty:Number(c.q)||1};}).filter(Boolean);
  }
  function updateCartPromo(){
    if(S.page!=='kasir')return;const box=document.querySelector('#uomCart');if(!box)return;document.querySelector('#pricePromoSummary')?.remove();const items=cartPricing();const savings=items.reduce((a,x)=>a+(x.basePrice-x.price)*x.qty,0);if(!savings)return;
    const promo=document.createElement('div');promo.id='pricePromoSummary';promo.className='notice';promo.style.marginTop='12px';promo.innerHTML=`<i>🏷</i><div><b>Harga promo aktif · Hemat ${fmt(savings)}</b><small>${items.filter(x=>x.best).map(x=>`${escv(x.p.name)} (${escv(x.best.pl.name)})`).join(' · ')}</small></div>`;box.appendChild(promo);
    const totals=box.querySelectorAll('.total');if(totals.length>=3){const sub=items.reduce((a,x)=>a+x.price*x.qty,0),tax=Math.round(sub*.11),total=sub+tax;const set=(el,val)=>{const target=el.querySelector('b,span:last-child');if(target)target.textContent=fmt(val);};set(totals[0],sub);set(totals[1],tax);set(totals[2],total);}
  }
  function selectedPL(){return (DB.priceLists||[]).find(x=>x.id===S.selectedPriceListId);}
  function lineRows(rules){return rules.map((r,i)=>`<tr data-pl-rule="${i}"><td><select class="pl-product"><option value="">Pilih produk</option>${DB.products.map(p=>`<option value="${p.id}" ${p.id===r.productId?'selected':''}>${escv(p.name)}</option>`).join('')}</select></td><td><select class="pl-mode"><option value="discount" ${r.fixedPrice==null?'selected':''}>Diskon %</option><option value="fixed" ${r.fixedPrice!=null?'selected':''}>Harga Tetap</option></select></td><td><input class="pl-discount" type="number" min="0" max="100" value="${r.discountPercent??''}" placeholder="10" ${r.fixedPrice!=null?'disabled':''}></td><td><input class="pl-fixed" type="number" min="0" value="${r.fixedPrice??''}" placeholder="25000" ${r.fixedPrice==null?'disabled':''}></td><td><button type="button" class="danger-btn" data-pl-remove="${i}">Hapus</button></td></tr>`).join('');}
  function openForm(existing){
    const pl=existing?JSON.parse(JSON.stringify(existing)):{id:uid('pl'),name:'',type:'Customer Group',customerIds:[],dateRange:{start:'',end:''},rules:[{productId:'',discountPercent:'',fixedPrice:null}],status:'Aktif'};
    const draw=()=>modal(existing?'Edit Price List':'Buat Price List',`<div class="form"><label>Nama Price List<input id="plName" value="${escv(pl.name)}" placeholder="Contoh: Harga Klinik Sehat"/></label><label>Jenis Target<select id="plType"><option ${pl.type==='Customer Group'?'selected':''}>Customer Group</option><option ${pl.type==='Promo Periode'?'selected':''}>Promo Periode</option></select></label><label>Status<select id="plStatus"><option ${pl.status!=='Nonaktif'?'selected':''}>Aktif</option><option ${pl.status==='Nonaktif'?'selected':''}>Nonaktif</option></select></label></div><div id="plTarget">${targetFields(pl)}</div><div style="height:10px"></div><div class="title"><span>Aturan Harga Produk</span><button type="button" class="outline" id="plAddRule">＋ Tambah Produk</button></div><p class="muted">Pilih salah satu: diskon persen atau harga tetap. Sistem memilih harga aktif terendah bila beberapa price list cocok.</p><div style="overflow:auto"><table><thead><tr><th>Produk</th><th>Metode</th><th>Diskon %</th><th>Harga Tetap</th><th></th></tr></thead><tbody>${lineRows(pl.rules)}</tbody></table></div>`,()=>{
      const name=document.querySelector('#plName').value.trim();if(!name)return toast('Nama price list wajib diisi','err'),false;
      const type=document.querySelector('#plType').value;const rules=[];let invalid=false;document.querySelectorAll('[data-pl-rule]').forEach(row=>{const productId=row.querySelector('.pl-product').value,mode=row.querySelector('.pl-mode').value,d=Number(row.querySelector('.pl-discount').value),f=Number(row.querySelector('.pl-fixed').value);if(!productId)return;if(mode==='discount'&&!(d>0&&d<=100))invalid=true;if(mode==='fixed'&&!(f>=0))invalid=true;rules.push({productId,discountPercent:mode==='discount'?d:null,fixedPrice:mode==='fixed'?f:null});});if(!rules.length||invalid)return toast('Isi minimal satu aturan harga dengan nilai valid','err'),false;
      const payload={name,type,status:document.querySelector('#plStatus').value,rules,customerIds:type==='Customer Group'?[...document.querySelectorAll('[data-pl-customer]:checked')].map(x=>x.value):[],dateRange:type==='Promo Periode'?{start:document.querySelector('#plStart').value,end:document.querySelector('#plEnd').value}:{start:'',end:''}};
      if(type==='Customer Group'&&!payload.customerIds.length)return toast('Pilih minimal satu pelanggan target','err'),false;if(type==='Promo Periode'&&(!payload.dateRange.start||!payload.dateRange.end||payload.dateRange.end<payload.dateRange.start))return toast('Rentang promo tidak valid','err'),false;
      if(existing)Object.assign(existing,payload);else DB.priceLists.unshift({...pl,...payload});saveDB();render();toast(existing?'Price list diperbarui':'Price list dibuat');
    },{saveLabel:'Simpan Price List'});bindForm(pl,draw);};draw();}
  function targetFields(pl){if(pl.type==='Customer Group')return `<div class="card" style="padding:12px"><b>Target Pelanggan</b><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:8px;margin-top:10px">${DB.customers.map(c=>`<label style="display:flex;gap:7px;align-items:center"><input type="checkbox" data-pl-customer value="${c.id}" ${(pl.customerIds||[]).includes(c.id)?'checked':''}> ${escv(c.name)}</label>`).join('')||'<span class="muted">Belum ada pelanggan terdaftar.</span>'}</div></div>`;return `<div class="form"><label>Mulai Promo<input id="plStart" type="date" value="${escv(pl.dateRange?.start||'')}"></label><label>Akhir Promo<input id="plEnd" type="date" value="${escv(pl.dateRange?.end||'')}"></label></div>`;}
  function bindForm(pl,draw){const t=document.querySelector('#plType');if(t)t.onchange=()=>{pl.type=t.value;pl.customerIds=[...document.querySelectorAll('[data-pl-customer]:checked')].map(x=>x.value);pl.dateRange={start:document.querySelector('#plStart')?.value||'',end:document.querySelector('#plEnd')?.value||''};draw();};const add=document.querySelector('#plAddRule');if(add)add.onclick=()=>{pl.rules=readRules();pl.rules.push({productId:'',discountPercent:'',fixedPrice:null});draw();};document.querySelectorAll('[data-pl-remove]').forEach(b=>b.onclick=()=>{pl.rules=readRules();pl.rules.splice(Number(b.dataset.plRemove),1);draw();});document.querySelectorAll('[data-pl-rule]').forEach(row=>{const mode=row.querySelector('.pl-mode');mode.onchange=()=>{row.querySelector('.pl-discount').disabled=mode.value!=='discount';row.querySelector('.pl-fixed').disabled=mode.value!=='fixed';};});}
  function readRules(){return [...document.querySelectorAll('[data-pl-rule]')].map(r=>{const mode=r.querySelector('.pl-mode').value;return {productId:r.querySelector('.pl-product').value,discountPercent:mode==='discount'?r.querySelector('.pl-discount').value:null,fixedPrice:mode==='fixed'?r.querySelector('.pl-fixed').value:null};});}
  function detail(pl){const active=isActive(pl,S.cartCustomerId,today());return `<section class="page active"><div class="head"><div><button class="outline" data-pl-back>← Kembali ke Price List</button><h2 style="margin-top:14px">${escv(pl.name)}</h2><p>${escv(pl.type)} · ${status(pl.status,pl.status==='Aktif'?'ok':'warn')}</p></div><button class="outline" data-pl-edit="${pl.id}">Edit</button></div><div class="card" style="padding:18px"><div class="grid4"><div><label class="muted">Jenis Target</label><b>${escv(pl.type)}</b></div><div><label class="muted">Target</label><b>${pl.type==='Customer Group'?(pl.customerIds||[]).length+' pelanggan':(pl.dateRange?.start||'-')+' s.d. '+(pl.dateRange?.end||'-')}</b></div><div><label class="muted">Aturan Produk</label><b>${(pl.rules||[]).length} produk</b></div><div><label class="muted">Status Hari Ini</label><b>${pl.type==='Promo Periode'?(isActive(pl,null,today())?'Aktif':'Tidak Aktif'):'Berdasarkan pelanggan'}</b></div></div></div><div style="height:16px"></div><div class="card"><div class="title"><span>Aturan Harga</span></div><table><thead><tr><th>Produk</th><th>Harga Normal</th><th>Diskon</th><th>Harga Promo</th></tr></thead><tbody>${(pl.rules||[]).map(r=>{const p=DB.products.find(x=>x.id===r.productId),u=unit(p,p?.saleUnit),n=normalPrice(p,u.code),promo=r.fixedPrice!=null?Number(r.fixedPrice):Math.round(n*(1-(Number(r.discountPercent)||0)/100));return `<tr><td><b>${escv(p?.name||'Produk dihapus')}</b></td><td>${fmt(n)}</td><td>${r.fixedPrice!=null?'-':(r.discountPercent||0)+'%'}</td><td><b style="color:var(--g)">${fmt(promo)}</b></td></tr>`;}).join('')}</tbody></table></div></section>`;}
  function list(){const lists=DB.priceLists||[];return `<section class="page active"><div class="head"><div><h2>Price List & Diskon</h2><p>Atur harga khusus pelanggan dan promo harga berdasarkan periode.</p></div><button class="primary" data-pl-new>＋ Buat Price List</button></div><div class="grid4"><div class="card kpi"><div class="kicon">🏷</div><div><label>Total Price List</label><strong>${lists.length}</strong><span class="muted">Master tersimpan</span></div></div><div class="card kpi"><div class="kicon">✓</div><div><label>Aktif</label><strong>${lists.filter(x=>x.status==='Aktif').length}</strong><span class="muted">Dapat dipakai</span></div></div><div class="card kpi"><div class="kicon">◌</div><div><label>Promo Periode Aktif</label><strong>${lists.filter(x=>x.type==='Promo Periode'&&isActive(x,null,today())).length}</strong><span class="muted">Hari ini</span></div></div><div class="card kpi"><div class="kicon">♙</div><div><label>Price List Customer</label><strong>${lists.filter(x=>x.type==='Customer Group').length}</strong><span class="muted">Harga khusus</span></div></div></div><div style="height:16px"></div><div class="card"><table><thead><tr><th>Nama</th><th>Jenis</th><th>Target</th><th>Produk</th><th>Status</th></tr></thead><tbody>${lists.length?lists.map(pl=>`<tr class="clickable" data-pl-open="${pl.id}"><td><b>${escv(pl.name)}</b></td><td>${escv(pl.type)}</td><td>${pl.type==='Customer Group'?(pl.customerIds||[]).length+' pelanggan':escv(pl.dateRange?.start||'-')+' s.d. '+escv(pl.dateRange?.end||'-')}</td><td>${(pl.rules||[]).length} produk</td><td>${status(pl.status,pl.status==='Aktif'?'ok':'warn')}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Belum ada price list.</td></tr>'}</tbody></table></div></section>`;}
  function injectCustomerPrices(){if(S.page!=='pelanggan'||!S.selectedCustomerId)return;const c=DB.customers.find(x=>x.id===S.selectedCustomerId),page=document.querySelector('#pages .page');if(!c||!page||document.querySelector('#customerPriceLists'))return;const match=(DB.priceLists||[]).filter(pl=>isActive(pl,c.id,today()));const box=document.createElement('div');box.className='card';box.id='customerPriceLists';box.style.marginTop='16px';box.innerHTML=`<div class="title"><span>Price List Berlaku</span><span class="muted">${match.length} aktif</span></div>${match.length?match.map(pl=>`<div class="notice"><i>🏷</i><div><b>${escv(pl.name)}</b><small>${escv(pl.type)} · ${(pl.rules||[]).length} aturan harga</small></div></div>`).join(''):'<p class="empty">Tidak ada price list aktif untuk pelanggan ini.</p>'}`;page.appendChild(box);}
  function applyCheckoutPromo(){const pricing=cartPricing();if(!pricing.some(x=>x.best))return null;const backups=[];pricing.forEach(x=>{if(!x.best)return;const u=unit(x.p,x.code);backups.push({u,price:u.price,basePrice:u.basePrice});u.basePrice=u.basePrice??u.price;u.price=x.price;});return {pricing,backups};}
  const oldCheckout=checkout;checkout=function(){const ctx=applyCheckoutPromo();const before=DB.transactions.length;const out=oldCheckout();if(ctx){const tx=(DB.transactions||[])[0]||DB.transactions[DB.transactions.length-1];if(DB.transactions.length>before&&tx){tx.items=(tx.items||[]).map(it=>{const x=ctx.pricing.find(z=>z.p.id===it.productId&&z.code===(it.unitCode||z.code));return x?{...it,originalPrice:x.basePrice,price:x.price,discountAmount:(x.basePrice-x.price)*(Number(it.qty)||0),priceListId:x.best?.pl.id||null,priceListName:x.best?.pl.name||null}:it;});tx.priceListIds=[...new Set(ctx.pricing.filter(x=>x.best).map(x=>x.best.pl.id))];saveDB();}ctx.backups.forEach(b=>{b.u.price=b.price;if(b.basePrice===undefined)delete b.u.basePrice;});}return out;};
  const baseRender=render;render=function(){if(S.page==='price-list'){nav();document.querySelector('#pages').innerHTML=selectedPL()?detail(selectedPL()):list();bind();return;}baseRender();updateCartPromo();injectCustomerPrices();};
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;S.selectedPriceListId=null;render();});document.querySelectorAll('[data-pl-new]').forEach(b=>b.onclick=()=>openForm());document.querySelectorAll('[data-pl-open]').forEach(b=>b.onclick=()=>{S.selectedPriceListId=b.dataset.plOpen;render();});document.querySelectorAll('[data-pl-back]').forEach(b=>b.onclick=()=>{S.selectedPriceListId=null;render();});document.querySelectorAll('[data-pl-edit]').forEach(b=>b.onclick=()=>openForm(DB.priceLists.find(x=>x.id===b.dataset.plEdit)));}
})();
