/* Retur Pembelian dan Retur Penjualan */
(function(){
  DB.purchaseReturns=DB.purchaseReturns||[];
  DB.salesReturns=DB.salesReturns||[];
  const ix=NAV.findIndex(x=>x[0]==='pembelian');
  if(!NAV.some(x=>x[0]==='retur')) NAV.splice(ix<0?NAV.length:ix+1,0,['retur','↩','Retur']);
  const purchaseReasons=['Rusak','Kadaluarsa','Salah Kirim'];
  const salesReasons=['Produk Rusak','Salah Produk','Tidak Sesuai Pesanan','Lainnya'];
  function dt(v){return v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';}
  function pOf(id){return DB.products.find(p=>p.id===id);}
  function uom(p,code){return p?.units?.find(x=>x.code===code)||p?.units?.find(x=>x.code===p?.baseUnit)||{code:p?.baseUnit||'UNIT',label:p?.type||'Unit',factorToBase:1,price:p?.price||0,cost:p?.cost||0};}
  function baseQty(it){return Number(it.baseQty??it.qty)||0;}
  function displayQty(it,p){return Number(it.displayQty??it.qty)||0;}
  function returnedPurchase(poId,productId){return DB.purchaseReturns.filter(r=>r.poId===poId&&r.status==='Selesai').flatMap(r=>r.items||[]).filter(i=>i.productId===productId).reduce((a,i)=>a+baseQty(i),0);}
  function returnedSales(txId,productId){return DB.salesReturns.filter(r=>r.transactionId===txId&&r.status==='Selesai').flatMap(r=>r.items||[]).filter(i=>i.productId===productId).reduce((a,i)=>a+baseQty(i),0);}
  function money(n){return fmt(Number(n)||0);}
  function formPurchaseReturn(poId){
    const po=DB.purchaseOrders.find(x=>x.id===poId);if(!po||po.status!=='Selesai')return toast('Retur hanya dapat dibuat dari PO selesai','err');
    const lines=(po.items||[]).map((it,i)=>{const p=pOf(it.productId),u=uom(p,it.unitCode||p?.purchaseUnit),original=baseQty(it),returned=returnedPurchase(po.id,it.productId),available=Math.max(0,original-returned),maxDisplay=available/u.factorToBase;return {i,it,p,u,available,maxDisplay};}).filter(x=>x.available>0);
    if(!lines.length)return toast('Semua item PO ini sudah diretur','err');
    modal('Buat Retur Pembelian',`<div class="form"><div class="card" style="padding:10px"><b>${esc(po.code)}</b><br><small class="muted">Vendor: ${esc(po.supplier||'-')}</small></div><label>Catatan Retur<input id="prNote" placeholder="Contoh: Barang rusak saat diterima"/></label></div><div style="overflow:auto"><table><thead><tr><th>Produk</th><th>Maks. Retur</th><th>Qty Retur</th><th>Alasan</th><th>Nilai</th></tr></thead><tbody>${lines.map(x=>`<tr data-pr-line="${x.i}"><td><b>${esc(x.p?.name||'Produk')}</b><br><small class="muted">${esc(x.u.label)}</small></td><td>${x.maxDisplay} ${esc(x.u.label)}<br><small class="muted">(${x.available} base)</small></td><td><input class="prQty" type="number" min="0" max="${x.maxDisplay}" value="0" style="width:92px"></td><td><select class="prReason" disabled><option value="">Pilih alasan</option>${purchaseReasons.map(r=>`<option>${r}</option>`).join('')}</select></td><td class="prValue">${money(0)}</td></tr>`).join('')}</tbody></table></div>`,()=>{
      const items=[];document.querySelectorAll('[data-pr-line]').forEach(row=>{const x=lines.find(z=>z.i===Number(row.dataset.prLine)),qty=Math.max(0,Number(row.querySelector('.prQty').value)||0),reason=row.querySelector('.prReason').value;if(!qty)return;if(qty>x.maxDisplay+0.00001)throw new Error('Melebihi jumlah tersedia');if(!reason)return;items.push({productId:x.it.productId,qty:qty*x.u.factorToBase,baseQty:qty*x.u.factorToBase,displayQty:qty,unitCode:x.u.code,unitLabel:x.u.label,cost:Number(x.it.cost??x.u.cost)||0,reason});});
      if(!items.length)return toast('Pilih minimal satu item retur dan alasan','err'),false;
      const incomplete=[...document.querySelectorAll('[data-pr-line]')].some(r=>Number(r.querySelector('.prQty').value)>0&&!r.querySelector('.prReason').value);if(incomplete)return toast('Alasan retur wajib dipilih','err'),false;
      const ret={id:uid('pr'),code:'RB-'+String(Date.now()).slice(-8),poId:po.id,supplierId:po.supplierId,date:Date.now(),items,value:items.reduce((a,i)=>a+i.displayQty*i.cost,0),note:document.querySelector('#prNote').value.trim(),status:'Selesai'};
      items.forEach(it=>{const p=pOf(it.productId);if(!p||p.stock<it.baseQty)throw new Error('Stok tidak cukup');p.stock-=it.baseQty;p.batches=p.batches||[];p.batches.push({batchNo:'RB-'+ret.code,received:new Date().toISOString().slice(0,10),expired:p.expired,qty:-it.baseQty,location:'Retur ke Vendor'});});
      DB.purchaseReturns.unshift(ret);saveDB();render();toast('Retur pembelian selesai dan stok dikurangi');
    },{saveLabel:'Selesaikan Retur'});
    bindPurchaseForm(lines);
  }
  function bindPurchaseForm(lines){document.querySelectorAll('[data-pr-line]').forEach(row=>{const x=lines.find(z=>z.i===Number(row.dataset.prLine)),qty=row.querySelector('.prQty'),reason=row.querySelector('.prReason'),value=row.querySelector('.prValue');const redraw=()=>{const q=Math.max(0,Number(qty.value)||0);reason.disabled=q===0;if(q===0)reason.value='';value.textContent=money(q*(Number(x.it.cost??x.u.cost)||0));};qty.oninput=redraw;reason.onchange=redraw;});}
  function formSalesReturn(txId){
    const tx=DB.transactions.find(x=>x.id===txId);if(!tx)return toast('Transaksi tidak ditemukan','err');
    const lines=(tx.items||[]).map((it,i)=>{const p=pOf(it.productId),u=uom(p,it.unitCode||p?.saleUnit),original=baseQty(it),returned=returnedSales(tx.id,it.productId),available=Math.max(0,original-returned),maxDisplay=available/u.factorToBase;return {i,it,p,u,available,maxDisplay};}).filter(x=>x.available>0);
    if(!lines.length)return toast('Semua item transaksi ini sudah diretur','err');
    modal('Retur Transaksi Penjualan',`<div class="form"><div class="card" style="padding:10px"><b>${esc(tx.code)}</b><br><small class="muted">Pelanggan: ${esc((DB.customers.find(c=>c.id===tx.customerId)||{}).name||'Pelanggan Umum')}</small></div><label>Metode Refund<select id="srRefund"><option>Tunai</option><option>Tukar Barang</option><option>Kredit Poin</option></select></label><label>Catatan Retur<input id="srNote" placeholder="Catatan tambahan"/></label></div><div style="overflow:auto"><table><thead><tr><th>Produk</th><th>Maks. Retur</th><th>Qty Retur</th><th>Alasan</th><th>Nilai Refund</th></tr></thead><tbody>${lines.map(x=>`<tr data-sr-line="${x.i}"><td><b>${esc(x.it.name||x.p?.name||'Produk')}</b><br><small class="muted">${esc(x.u.label)}</small></td><td>${x.maxDisplay} ${esc(x.u.label)}<br><small class="muted">(${x.available} base)</small></td><td><input class="srQty" type="number" min="0" max="${x.maxDisplay}" value="0" style="width:92px"></td><td><select class="srReason" disabled><option value="">Pilih alasan</option>${salesReasons.map(r=>`<option>${r}</option>`).join('')}</select></td><td class="srValue">${money(0)}</td></tr>`).join('')}</tbody></table></div>`,()=>{
      const items=[];document.querySelectorAll('[data-sr-line]').forEach(row=>{const x=lines.find(z=>z.i===Number(row.dataset.srLine)),qty=Math.max(0,Number(row.querySelector('.srQty').value)||0),reason=row.querySelector('.srReason').value;if(!qty)return;if(qty>x.maxDisplay+0.00001)throw new Error('Melebihi jumlah tersedia');if(!reason)return;items.push({productId:x.it.productId,qty:qty*x.u.factorToBase,baseQty:qty*x.u.factorToBase,displayQty:qty,unitCode:x.u.code,unitLabel:x.u.label,price:Number(x.it.price??x.u.price)||0,reason});});
      if(!items.length)return toast('Pilih minimal satu item retur dan alasan','err'),false;
      const incomplete=[...document.querySelectorAll('[data-sr-line]')].some(r=>Number(r.querySelector('.srQty').value)>0&&!r.querySelector('.srReason').value);if(incomplete)return toast('Alasan retur wajib dipilih','err'),false;
      const refundMethod=document.querySelector('#srRefund').value;const ret={id:uid('sr'),code:'RJ-'+String(Date.now()).slice(-8),transactionId:tx.id,customerId:tx.customerId,date:Date.now(),items,value:items.reduce((a,i)=>a+i.displayQty*i.price,0),refundMethod,note:document.querySelector('#srNote').value.trim(),status:'Selesai'};
      items.forEach(it=>{const p=pOf(it.productId);if(!p)return;p.stock+=it.baseQty;p.batches=p.batches||[];p.batches.push({batchNo:'RJ-'+ret.code,received:new Date().toISOString().slice(0,10),expired:p.expired,qty:it.baseQty,location:'Retur Penjualan'});});
      if(tx.customerId){const c=DB.customers.find(x=>x.id===tx.customerId);if(c)c.points=Math.max(0,(Number(c.points)||0)-Math.floor(ret.value/10000));}
      DB.salesReturns.unshift(ret);saveDB();render();toast('Retur penjualan selesai, stok dan poin diperbarui');
    },{saveLabel:'Selesaikan Retur'});
    bindSalesForm(lines);
  }
  function bindSalesForm(lines){document.querySelectorAll('[data-sr-line]').forEach(row=>{const x=lines.find(z=>z.i===Number(row.dataset.srLine)),qty=row.querySelector('.srQty'),reason=row.querySelector('.srReason'),value=row.querySelector('.srValue');const redraw=()=>{const q=Math.max(0,Number(qty.value)||0);reason.disabled=q===0;if(q===0)reason.value='';value.textContent=money(q*(Number(x.it.price??x.u.price)||0));};qty.oninput=redraw;reason.onchange=redraw;});}
  function returnRows(list,type){return list.length?list.map(r=>{const source=type==='purchase'?DB.purchaseOrders.find(x=>x.id===r.poId):DB.transactions.find(x=>x.id===r.transactionId);const partner=type==='purchase'?(DB.suppliers.find(x=>x.id===r.supplierId)||{}).name:(DB.customers.find(x=>x.id===r.customerId)||{}).name||'Pelanggan Umum';return `<tr><td><b>${esc(r.code)}</b></td><td>${dt(r.date)}</td><td>${esc(source?.code||'-')}</td><td>${esc(partner||'-')}</td><td>${(r.items||[]).length} produk</td><td>${money(r.value)}</td><td>${status(r.status,'ok')}</td></tr>`;}).join(''):'<tr><td colspan="7" class="empty">Belum ada retur.</td></tr>';}
  function returnsPage(){const pr=DB.purchaseReturns||[],sr=DB.salesReturns||[];return `<section class="page active"><div class="head"><div><h2>Retur Pembelian & Penjualan</h2><p>Riwayat barang yang dikembalikan ke vendor atau diterima kembali dari pelanggan.</p></div></div><div class="grid4"><div class="card kpi"><div class="kicon">↩</div><div><label>Retur Pembelian</label><strong>${pr.length}</strong><span class="muted">Ke vendor</span></div></div><div class="card kpi"><div class="kicon">↪</div><div><label>Nilai Retur Beli</label><strong>${money(pr.reduce((a,x)=>a+(Number(x.value)||0),0))}</strong><span class="muted">Total selesai</span></div></div><div class="card kpi"><div class="kicon">↩</div><div><label>Retur Penjualan</label><strong>${sr.length}</strong><span class="muted">Dari pelanggan</span></div></div><div class="card kpi"><div class="kicon">↪</div><div><label>Nilai Refund</label><strong>${money(sr.reduce((a,x)=>a+(Number(x.value)||0),0))}</strong><span class="muted">Total selesai</span></div></div></div><div style="height:16px"></div><div class="two"><div class="card"><div class="title"><span>Retur Pembelian</span><span class="muted">Berasal dari PO selesai</span></div><table><thead><tr><th>No Retur</th><th>Tanggal</th><th>PO</th><th>Vendor</th><th>Item</th><th>Nilai</th><th>Status</th></tr></thead><tbody>${returnRows(pr,'purchase')}</tbody></table></div><div class="card"><div class="title"><span>Retur Penjualan</span><span class="muted">Berasal dari transaksi kasir</span></div><table><thead><tr><th>No Retur</th><th>Tanggal</th><th>Transaksi</th><th>Pelanggan</th><th>Item</th><th>Nilai</th><th>Status</th></tr></thead><tbody>${returnRows(sr,'sales')}</tbody></table></div></div></section>`;}
  function enhanceSourceButtons(){
    if(S.page==='pembelian'&&S.selectedPOId){const po=DB.purchaseOrders.find(x=>x.id===S.selectedPOId);const area=document.querySelector('#pages .head .tabs');if(po?.status==='Selesai'&&area&&!area.querySelector('[data-return-purchase]')){const b=document.createElement('button');b.className='outline';b.textContent='↩ Buat Retur';b.dataset.returnPurchase=po.id;area.appendChild(b);}}
    if(S.page==='penjualan'&&S.selectedSaleId){const tx=DB.transactions.find(x=>x.id===S.selectedSaleId);const head=document.querySelector('#pages .head');if(tx&&head&&!head.querySelector('[data-return-sales]')){const b=document.createElement('button');b.className='outline';b.textContent='↩ Retur Transaksi Ini';b.dataset.returnSales=tx.id;const target=head.querySelector('.tabs')||head.querySelector('div:last-child');target?.appendChild(b);}}
  }
  const oldRender=render;render=function(){if(S.page==='retur'){nav();document.querySelector('#pages').innerHTML=returnsPage();bind();return;}oldRender();enhanceSourceButtons();};
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;render();});}
  document.addEventListener('click',e=>{const pb=e.target.closest('[data-return-purchase]');if(pb){e.preventDefault();e.stopImmediatePropagation();formPurchaseReturn(pb.dataset.returnPurchase);return;}const sb=e.target.closest('[data-return-sales]');if(sb){e.preventDefault();e.stopImmediatePropagation();formSalesReturn(sb.dataset.returnSales);}},true);
})();
