/* Stock Opname & Adjustment */
(function(){
  DB.stockOpnames=DB.stockOpnames||[];
  const navIndex=NAV.findIndex(x=>x[0]==='inventori');
  if(!NAV.some(x=>x[0]==='stock-opname')) NAV.splice(navIndex<0?NAV.length:navIndex+1,0,['stock-opname','◫','Stock Opname']);
  const REASONS=['Rusak','Kadaluarsa','Hilang','Kesalahan Input','Lainnya'];
  function dateText(v){return v?new Date(v).toLocaleString('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'-';}
  function tone(s){return s==='Selesai'?'ok':'violet';}
  function productUnit(p){return p?.units?.find(x=>x.code===p.baseUnit)?.label||p?.type||'unit';}
  function getSO(){return DB.stockOpnames.find(x=>x.id===S.selectedStockOpnameId);}
  function rows(list){return list.length?list.sort((a,b)=>(b.date||0)-(a.date||0)).map(so=>{const diffs=(so.items||[]).filter(x=>Number(x.diff)!==0);return `<tr class="clickable" data-so-open="${so.id}"><td><b>${esc(so.code)}</b></td><td>${dateText(so.date)}</td><td>${(so.items||[]).length} produk</td><td>${diffs.length?`${diffs.length} selisih`:'Tidak ada'}</td><td>${status(so.status,tone(so.status))}</td><td>${esc(so.note||'-')}</td></tr>`;}).join(''):'<tr><td colspan="6" class="empty">Belum ada stock opname.</td></tr>';}
  function listPage(){const all=DB.stockOpnames||[],draft=all.filter(x=>x.status==='Draft').length,done=all.filter(x=>x.status==='Selesai').length;return `<section class="page active"><div class="head"><div><h2>Stock Opname & Adjustment</h2><p>Bandingkan stok fisik dengan stok sistem dan catat alasan setiap selisih.</p></div><button class="primary" data-so-start>＋ Mulai Stock Opname</button></div><div class="grid4"><div class="card kpi"><div class="kicon">◫</div><div><label>Total Opname</label><strong>${all.length}</strong><span class="muted">Riwayat tercatat</span></div></div><div class="card kpi"><div class="kicon">◴</div><div><label>Draft</label><strong>${draft}</strong><span class="muted">Belum diposting</span></div></div><div class="card kpi"><div class="kicon">✓</div><div><label>Selesai</label><strong>${done}</strong><span class="muted">Adjustment diposting</span></div></div><div class="card kpi"><div class="kicon">!</div><div><label>Selisih Terakhir</label><strong>${all[0]?(all[0].items||[]).filter(x=>x.diff!==0).length:0}</strong><span class="muted">Baris berbeda</span></div></div></div><div style="height:16px"></div><div class="card"><div class="title"><span>Riwayat Stock Opname</span><span class="muted">Klik baris untuk detail</span></div><table><thead><tr><th>No. Opname</th><th>Tanggal</th><th>Produk</th><th>Selisih</th><th>Status</th><th>Catatan</th></tr></thead><tbody>${rows(all)}</tbody></table></div></section>`;}
  function start(){
    modal('Mulai Stock Opname',`<div class="form"><label>Kategori Produk<select id="soCategory"><option value="">Semua Kategori</option>${[...new Set(DB.products.map(p=>p.cat))].sort().map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select></label><label>Catatan Opname<input id="soNote" placeholder="Contoh: Opname bulanan gudang pusat"/></label><p class="muted">Stok sistem akan disalin saat draft dibuat. Isi stok fisik pada halaman detail setelah menghitung barang.</p></div>`,()=>{
      const cat=document.querySelector('#soCategory').value;const products=DB.products.filter(p=>!cat||p.cat===cat);if(!products.length)return toast('Tidak ada produk pada kategori ini','err'),false;
      const so={id:uid('so'),code:'SO-'+String(Date.now()).slice(-8),date:Date.now(),status:'Draft',category:cat||'Semua',note:document.querySelector('#soNote').value.trim(),items:products.map(p=>({productId:p.id,systemQty:Number(p.stock)||0,physicalQty:Number(p.stock)||0,diff:0,reason:''}))};
      DB.stockOpnames.unshift(so);saveDB();S.selectedStockOpnameId=so.id;S.page='stock-opname';render();toast('Draft stock opname dibuat');
    },{saveLabel:'Buat Draft'});
  }
  function detail(){
    const so=getSO();if(!so){S.selectedStockOpnameId=null;return listPage();}
    const different=(so.items||[]).filter(x=>Number(x.diff)!==0);const actions=so.status==='Draft'?`<button class="outline" data-so-save="${so.id}">Simpan Draft</button><button class="primary" data-so-finish="${so.id}">Selesaikan Opname</button>`:`<button class="outline" data-so-print="${so.id}">Cetak</button>`;
    return `<section class="page active"><div class="head"><div><button class="outline" data-so-back>← Kembali ke Stock Opname</button><h2 style="margin-top:14px">Detail Stock Opname</h2><p>${esc(so.code)} · ${dateText(so.date)} · Kategori: ${esc(so.category||'Semua')}</p></div><div class="tabs">${actions}</div></div><div class="card" style="padding:18px"><div class="grid4"><div><label class="muted">Status</label><p>${status(so.status,tone(so.status))}</p></div><div><label class="muted">Produk Dihitung</label><b>${so.items.length} produk</b></div><div><label class="muted">Ada Selisih</label><b>${different.length} produk</b></div><div><label class="muted">Catatan</label><b>${esc(so.note||'-')}</b></div></div></div><div style="height:16px"></div><div class="card"><div class="title"><span>Perhitungan Fisik</span><span class="muted">Qty menggunakan satuan dasar produk</span></div><div style="overflow:auto"><table><thead><tr><th>Produk</th><th>Kategori</th><th>Stok Sistem</th><th>Stok Fisik</th><th>Selisih</th><th>Alasan</th></tr></thead><tbody>${so.items.map((it,i)=>{const p=DB.products.find(x=>x.id===it.productId);const unit=productUnit(p),diff=Number(it.physicalQty)-Number(it.systemQty);return `<tr data-so-row="${i}"><td><b>${esc(p?.name||'Produk tidak ditemukan')}</b><br><small class="muted">${esc(unit)}</small></td><td>${esc(p?.cat||'-')}</td><td><b>${it.systemQty}</b> ${esc(unit)}</td><td>${so.status==='Draft'?`<input class="so-physical" type="number" min="0" value="${it.physicalQty}" style="width:100px">`:`<b>${it.physicalQty}</b>`} ${esc(unit)}</td><td class="so-diff" style="font-weight:900;color:${diff===0?'var(--muted)':diff>0?'var(--g)':'var(--red)'}">${diff>0?'+':''}${diff} ${esc(unit)}</td><td>${so.status==='Draft'?`<select class="so-reason" ${diff===0?'disabled':''}><option value="">${diff===0?'Tidak ada selisih':'Pilih alasan'}</option>${REASONS.map(r=>`<option ${it.reason===r?'selected':''}>${r}</option>`).join('')}</select>`:`${diff===0?'<span class="muted">-</span>':esc(it.reason||'-')}`}</td></tr>`;}).join('')}</tbody></table></div></div></section>`;
  }
  function syncInputs(){const so=getSO();if(!so||so.status!=='Draft')return;document.querySelectorAll('[data-so-row]').forEach(row=>{const i=Number(row.dataset.soRow),it=so.items[i],physical=Math.max(0,Number(row.querySelector('.so-physical').value)||0);it.physicalQty=physical;it.diff=physical-Number(it.systemQty||0);const reason=row.querySelector('.so-reason');if(reason)it.reason=reason.value;});}
  function updateRow(row){const so=getSO(),i=Number(row.dataset.soRow),it=so.items[i],p=DB.products.find(x=>x.id===it.productId),unit=productUnit(p);it.physicalQty=Math.max(0,Number(row.querySelector('.so-physical').value)||0);it.diff=it.physicalQty-Number(it.systemQty||0);const diff=row.querySelector('.so-diff'),reason=row.querySelector('.so-reason');diff.textContent=(it.diff>0?'+':'')+it.diff+' '+unit;diff.style.color=it.diff===0?'var(--muted)':it.diff>0?'var(--g)':'var(--red)';reason.disabled=it.diff===0;if(it.diff===0){it.reason='';reason.value='';}saveDB();}
  function adjustBatches(p,diff,code){
    p.batches=p.batches||[];
    if(diff>0){p.batches.push({batchNo:'SO-'+code,received:new Date().toISOString().slice(0,10),expired:p.expired,qty:diff,location:'Stock Adjustment'});return;}
    let remaining=Math.abs(diff);for(const b of p.batches){if(remaining<=0)break;const take=Math.min(Number(b.qty)||0,remaining);b.qty=(Number(b.qty)||0)-take;remaining-=take;}p.batches=p.batches.filter(b=>Number(b.qty)>0);
  }
  function finish(id){
    const so=DB.stockOpnames.find(x=>x.id===id);if(!so)return;syncInputs();const invalid=so.items.find(x=>Number(x.diff)!==0&&!x.reason);if(invalid)return toast('Semua produk dengan selisih wajib memiliki alasan','err');
    so.items.forEach(it=>{const p=DB.products.find(x=>x.id===it.productId);if(!p||Number(it.diff)===0)return;adjustBatches(p,Number(it.diff),so.code);p.stock=Number(it.physicalQty)||0;});
    so.status='Selesai';so.completedAt=Date.now();saveDB();render();toast('Stock opname selesai dan adjustment diposting');
  }
  function printSO(id){const so=DB.stockOpnames.find(x=>x.id===id);if(!so)return;const w=window.open('','_blank','width=900,height=700');if(!w)return toast('Izinkan pop-up untuk mencetak','err');w.document.write(`<html><head><title>${esc(so.code)}</title><style>body{font-family:Arial;padding:32px}table{border-collapse:collapse;width:100%;margin-top:18px}th,td{border:1px solid #bbb;padding:8px;text-align:left}th{background:#eef8f2}</style></head><body><h2>ApotekKilat — Stock Opname</h2><p><b>${esc(so.code)}</b><br>${dateText(so.date)}<br>Status: ${esc(so.status)}<br>Catatan: ${esc(so.note||'-')}</p><table><thead><tr><th>Produk</th><th>Sistem</th><th>Fisik</th><th>Selisih</th><th>Alasan</th></tr></thead><tbody>${so.items.map(it=>{const p=DB.products.find(x=>x.id===it.productId);return `<tr><td>${esc(p?.name||'Produk')}</td><td>${it.systemQty}</td><td>${it.physicalQty}</td><td>${it.diff}</td><td>${esc(it.reason||'-')}</td></tr>`;}).join('')}</tbody></table><script>window.onload=()=>window.print()<\/script></body></html>`);w.document.close();}
  const baseRender=render;render=function(){if(S.page==='stock-opname'){nav();document.querySelector('#pages').innerHTML=S.selectedStockOpnameId?detail():listPage();bind();return;}baseRender();if(S.page==='inventori')enhanceInventory();};
  function enhanceInventory(){const head=document.querySelector('#pages .head');if(!head||head.dataset.soButton)return;head.dataset.soButton='1';const target=head.querySelector('div:last-child');if(target){const b=document.createElement('button');b.className='outline';b.textContent='◫ Stock Opname';b.dataset.soStart='1';target.prepend(b);}}
  function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{S.page=b.dataset.page;S.selectedStockOpnameId=null;render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b));document.querySelectorAll('[data-so-start]').forEach(b=>b.onclick=start);document.querySelectorAll('[data-so-back]').forEach(b=>b.onclick=()=>{S.selectedStockOpnameId=null;render();});document.querySelectorAll('[data-so-open]').forEach(b=>b.onclick=()=>{S.selectedStockOpnameId=b.dataset.soOpen;render();});document.querySelectorAll('[data-so-save]').forEach(b=>b.onclick=()=>{syncInputs();saveDB();toast('Draft opname disimpan');});document.querySelectorAll('[data-so-finish]').forEach(b=>b.onclick=()=>finish(b.dataset.soFinish));document.querySelectorAll('[data-so-print]').forEach(b=>b.onclick=()=>printSO(b.dataset.soPrint));document.querySelectorAll('[data-so-row]').forEach(r=>{const p=r.querySelector('.so-physical');if(p)p.oninput=()=>updateRow(r);const reason=r.querySelector('.so-reason');if(reason)reason.onchange=()=>{syncInputs();saveDB();};});}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-so-start]');if(b){e.preventDefault();start();}},true);
})();
